apiVersion: 1
datasources:
  - name: InfluxDB v3 SQL
    uid: influxdb-v3-sql
    type: influxdb
    access: proxy
    url: http://localhost:8181
    isDefault: true
    editable: true
    jsonData:
      dbName: metrics
      version: Sql
      httpMode: GET
      tlsSkipVerify: true
    secureJsonData: {}